//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp2.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CancelRequest", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CancelRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestServiceKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RequestId {
            get {
                return this.RequestIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestIdField, value) != true)) {
                    this.RequestIdField = value;
                    this.RaisePropertyChanged("RequestId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RequestServiceKey {
            get {
                return this.RequestServiceKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestServiceKeyField, value) != true)) {
                    this.RequestServiceKeyField = value;
                    this.RaisePropertyChanged("RequestServiceKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CancelResponse", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CancelResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RequestId {
            get {
                return this.RequestIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestIdField, value) != true)) {
                    this.RequestIdField = value;
                    this.RaisePropertyChanged("RequestId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ResultCode {
            get {
                return this.ResultCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultCodeField, value) != true)) {
                    this.ResultCodeField = value;
                    this.RaisePropertyChanged("ResultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ResultMessage {
            get {
                return this.ResultMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultMessageField, value) != true)) {
                    this.ResultMessageField = value;
                    this.RaisePropertyChanged("ResultMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IListService")]
    public interface IListService {
        
        // CODEGEN: http://tempuri.org/ 네임스페이스의 요소 이름 requests이(가) "nillable"로 표시되지 않았으므로 메시지 계약을 생성합니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListService/GetResponses", ReplyAction="*")]
        ConsoleApp2.ServiceReference1.GetResponsesResponse GetResponses(ConsoleApp2.ServiceReference1.GetResponsesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListService/GetResponses", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp2.ServiceReference1.GetResponsesResponse> GetResponsesAsync(ConsoleApp2.ServiceReference1.GetResponsesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResponsesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResponses", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp2.ServiceReference1.GetResponsesRequestBody Body;
        
        public GetResponsesRequest() {
        }
        
        public GetResponsesRequest(ConsoleApp2.ServiceReference1.GetResponsesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetResponsesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleApp2.ServiceReference1.CancelRequest[] requests;
        
        public GetResponsesRequestBody() {
        }
        
        public GetResponsesRequestBody(ConsoleApp2.ServiceReference1.CancelRequest[] requests) {
            this.requests = requests;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResponsesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResponsesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp2.ServiceReference1.GetResponsesResponseBody Body;
        
        public GetResponsesResponse() {
        }
        
        public GetResponsesResponse(ConsoleApp2.ServiceReference1.GetResponsesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetResponsesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleApp2.ServiceReference1.CancelResponse[] GetResponsesResult;
        
        public GetResponsesResponseBody() {
        }
        
        public GetResponsesResponseBody(ConsoleApp2.ServiceReference1.CancelResponse[] GetResponsesResult) {
            this.GetResponsesResult = GetResponsesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IListServiceChannel : ConsoleApp2.ServiceReference1.IListService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListServiceClient : System.ServiceModel.ClientBase<ConsoleApp2.ServiceReference1.IListService>, ConsoleApp2.ServiceReference1.IListService {
        
        public ListServiceClient() {
        }
        
        public ListServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ListServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp2.ServiceReference1.GetResponsesResponse ConsoleApp2.ServiceReference1.IListService.GetResponses(ConsoleApp2.ServiceReference1.GetResponsesRequest request) {
            return base.Channel.GetResponses(request);
        }
        
        public ConsoleApp2.ServiceReference1.CancelResponse[] GetResponses(ConsoleApp2.ServiceReference1.CancelRequest[] requests) {
            ConsoleApp2.ServiceReference1.GetResponsesRequest inValue = new ConsoleApp2.ServiceReference1.GetResponsesRequest();
            inValue.Body = new ConsoleApp2.ServiceReference1.GetResponsesRequestBody();
            inValue.Body.requests = requests;
            ConsoleApp2.ServiceReference1.GetResponsesResponse retVal = ((ConsoleApp2.ServiceReference1.IListService)(this)).GetResponses(inValue);
            return retVal.Body.GetResponsesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp2.ServiceReference1.GetResponsesResponse> ConsoleApp2.ServiceReference1.IListService.GetResponsesAsync(ConsoleApp2.ServiceReference1.GetResponsesRequest request) {
            return base.Channel.GetResponsesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp2.ServiceReference1.GetResponsesResponse> GetResponsesAsync(ConsoleApp2.ServiceReference1.CancelRequest[] requests) {
            ConsoleApp2.ServiceReference1.GetResponsesRequest inValue = new ConsoleApp2.ServiceReference1.GetResponsesRequest();
            inValue.Body = new ConsoleApp2.ServiceReference1.GetResponsesRequestBody();
            inValue.Body.requests = requests;
            return ((ConsoleApp2.ServiceReference1.IListService)(this)).GetResponsesAsync(inValue);
        }
    }
}
